### ISSUE TITLE
Consider migrating database from H2 to SQLite

### ISSUE THREAD

**Issue by nanotaboada** [nanotaboada/java.samples.spring.boot#80]
## Description

The current application uses an **in-memory H2 database** that provides fast performance for development and testing but **loses all data when the application restarts**. To enable data persistence across application lifecycles while maintaining simplicity and portability, we should migrate to **SQLite** — a lightweight, file-based relational database that requires minimal configuration and has no separate server process.

### Current System Context

The Books API currently implements:
- **CRUD operations** for book management (create, read, update, delete)
- **Search functionality** via `/books/search?description={keyword}` using case-insensitive matching
- **Spring Cache** abstraction with `@Cacheable`, `@CachePut`, and `@CacheEvict` annotations
- **CLOB (Character Large Object)** handling for the `description` field via `@Lob` annotation
- **Custom JPQL queries** that use `CAST(b.description AS string)` for H2 CLOB compatibility
- **JPA auto-schema generation** from `@Entity` annotations

### Why Migrate?

| Aspect | H2 (In-Memory) | SQLite (File-Based) |
|--------|----------------|---------------------|
| **Data Persistence** | ❌ Lost on restart | ✅ Persists to disk |
| **Setup Complexity** | ✅ Zero config | ✅ Minimal (file path) |
| **Performance** | ✅ Fastest (RAM) | ⚠️ Slightly slower (disk I/O) |
| **Production Use** | ⚠️ Demo/testing only | ✅ Suitable for low-traffic apps |
| **Concurrent Writes** | ✅ Good | ⚠️ Limited (single writer) |
| **Docker Portability** | ✅ Embedded | ✅ Requires volume mount |
| **Resource Usage** | Higher (RAM) | Lower (disk) |

**Use Case Justification:**
- Enable demonstration of persistent data across deployments
- Better align with real-world application behavior
- Maintain simplicity without requiring external database servers (PostgreSQL, MySQL)
- Keep Docker image lightweight and self-contained

---

## Proposed Solution

Migrate from H2 to SQLite using the following approach:

1. **Replace H2 dependency** with Xerial SQLite JDBC driver in `pom.xml`
2. **Update database configuration** in `application.properties` to use SQLite connection string and dialect
3. **Modify repository queries** to handle TEXT fields instead of CLOB (remove `CAST` operations)
4. **Configure Docker volume** for database file persistence in `Dockerfile` and `compose.yaml`
5. **Validate all existing tests** pass without modification (no business logic changes)
6. **Document database file location** and backup strategy in README

### Technology Choices

- **Driver**: [Xerial SQLite JDBC](https://github.com/xerial/sqlite-jdbc) (most mature Java SQLite driver)
- **Hibernate Dialect**: `org.hibernate.community.dialect.SQLiteDialect` (available in Hibernate 6.2+)
- **File Location**: `/storage/books-sqlite3.db` within container, mapped to Docker volume
- **Schema Management**: Continue using JPA auto-DDL (`spring.jpa.hibernate.ddl-auto=update`)

---

### 1. Update Maven Dependencies (`pom.xml`)

Replace H2 dependency:

```xml
<!-- Remove this -->
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <scope>runtime</scope>
</dependency>

<!-- Add this -->
<dependency>
    <groupId>org.xerial</groupId>
    <artifactId>sqlite-jdbc</artifactId>
    <version>3.47.1.0</version>
</dependency>
<dependency>
    <groupId>org.hibernate.orm</groupId>
    <artifactId>hibernate-community-dialects</artifactId>
</dependency>
```

### 2. Update Database Configuration (`src/main/resources/application.properties`)

```properties
# SQLite Database Configuration
spring.datasource.url=jdbc:sqlite:${STORAGE_PATH:storage/books-sqlite3.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# JPA/Hibernate Configuration (keep existing)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
```

### 3. Simplify Repository Query (`BooksRepository.java`)

SQLite handles TEXT fields natively, so remove the `CAST` operation:

```java
@Repository
public interface BooksRepository extends CrudRepository<Book, String> {
    
    Optional<Book> findByIsbn(String isbn);
    
    // Simplified query - no CAST needed for SQLite TEXT
    @Query("SELECT b FROM Book b WHERE LOWER(b.description) LIKE LOWER(CONCAT('%', :keyword, '%'))")
    List<Book> findByDescriptionContainingIgnoreCase(@Param("keyword") String keyword);
}
```

### 4. Update Book Entity (`Book.java`)

Remove `@Lob` annotation since SQLite uses TEXT type automatically:

```java
@Entity
@Table(name = "books")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Book {
    @Id
    private String isbn;
    private String title;
    private String subtitle;
    private String author;
    private String publisher;
    @JsonDeserialize(using = LocalDateDeserializer.class)
    @JsonSerialize(using = LocalDateSerializer.class)
    private LocalDate published;
    private int pages;
    // Remove @Lob annotation - SQLite uses TEXT by default
    private String description;
    private String website;
}
```

### 5. Create Pre-Seeded SQLite Database

Create a `storage/` directory in the project root with a pre-seeded SQLite database file (`books-sqlite3.db`) containing the initial book data. This follows the same approach used in [ts-node-samples-express-restful](https://github.com/nanotaboada/ts-node-samples-express-restful).

### 6. Configure Docker Volume (`Dockerfile`)

Use a **"hold" pattern** where the pre-seeded database is stored inside the image, then copied to a volume on first run. This ensures:
- Fresh containers start with seed data
- Subsequent runs preserve user changes

```dockerfile
# ------------------------------------------------------------------------------
# Stage 1: Builder
# This stage builds the application and its dependencies.
# ------------------------------------------------------------------------------
FROM maven:3.9-eclipse-temurin-25-alpine AS builder

WORKDIR /app

# Copy pom.xml and download dependencies. This will be cached until pom.xml
# changes, speeding up the build process.
COPY pom.xml    .
RUN mvn dependency:go-offline -B

# Copy source code and build the application, skipping tests for faster builds.
COPY src        ./src
RUN mvn clean package -DskipTests

# ------------------------------------------------------------------------------
# Stage 2: Runtime
# This stage creates the final, minimal image to run the application.
# ------------------------------------------------------------------------------
FROM eclipse-temurin:25-jdk-alpine AS runtime

WORKDIR /app

# Install curl for health check
RUN apk add --no-cache curl

# Metadata labels for the image. These are useful for registries and inspection.
LABEL org.opencontainers.image.title="🧪 RESTful Web Service with Spring Boot"
LABEL org.opencontainers.image.description="Proof of Concept for a RESTful Web Service made with JDK 25 (LTS) and Spring Boot 4"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.source="https://github.com/nanotaboada/java.samples.spring.boot"

# https://rules.sonarsource.com/docker/RSPEC-6504/

# Copy application JAR file from the builder stage
COPY --from=builder     /app/target/*.jar           ./app.jar

# Copy metadata docs for container registries (e.g.: GitHub Container Registry)
COPY --chmod=444        README.md                   ./
COPY --chmod=555        assets/                     ./assets/

# Copy entrypoint and healthcheck scripts
COPY --chmod=555        scripts/entrypoint.sh       ./entrypoint.sh
COPY --chmod=555        scripts/healthcheck.sh      ./healthcheck.sh

# The 'hold' is our storage compartment within the image. Here, we copy a
# pre-seeded SQLite database file, which Compose will mount as a persistent
# 'storage' volume when the container starts up.
COPY --chmod=555        storage/                    ./hold/

# Install SQLite runtime libs, add non-root user and prepare volume mount point
RUN apk add --no-cache sqlite-libs && \
    addgroup -S spring && \
    adduser -S -G spring spring && \
    mkdir -p /storage && \
    chown -R spring:spring /storage

USER spring

EXPOSE 9000
EXPOSE 9001

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
    CMD ["./healthcheck.sh"]

ENTRYPOINT ["./entrypoint.sh"]
CMD ["java", "-jar", "./app.jar"]
```

### 7. Update Entrypoint Script (`scripts/entrypoint.sh`)

The entrypoint script handles copying the pre-seeded database from the image's `hold/` directory to the persistent volume on first run:

```bash
#!/bin/sh
set -e

echo "✔ Executing entrypoint script..."

IMAGE_STORAGE_PATH="/app/hold/books-sqlite3.db"
VOLUME_STORAGE_PATH="/storage/books-sqlite3.db"

echo "✔ Starting container..."

if [ ! -f "$VOLUME_STORAGE_PATH" ]; then
  echo "⚠️ No existing database file found in volume."
  if [ -f "$IMAGE_STORAGE_PATH" ]; then
    echo "Copying database file to writable volume..."
    cp "$IMAGE_STORAGE_PATH" "$VOLUME_STORAGE_PATH"
    echo "✔ Database initialized at $VOLUME_STORAGE_PATH"
  else
    echo "⚠️ Database file missing at $IMAGE_STORAGE_PATH"
    exit 1
  fi
else
  echo "✔ Existing database file found. Skipping seed copy."
fi

echo "✔ Ready!"
echo "🚀 Launching app..."
exec "$@"
```

### 8. Update Docker Compose (`compose.yaml`)

```yaml
name: java-samples-spring-boot

services:
  api:
    image: java-samples-spring-boot
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage:/storage/
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - STORAGE_PATH=/storage/books-sqlite3.db
    restart: unless-stopped

volumes:
  storage:
    name: java-samples-spring-boot_storage
```

### 9. Optional: Database Backup Script

Create `scripts/backup-db.sh` for SQLite database backups:

```bash
#!/bin/bash
# Backup SQLite database from Docker volume

CONTAINER_ID=$(docker compose ps -q api)
BACKUP_DIR="./backups"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

mkdir -p "$BACKUP_DIR"
docker cp "$CONTAINER_ID:/storage/books-sqlite3.db" "$BACKUP_DIR/books_$TIMESTAMP.db"
echo "✅ Backup created: $BACKUP_DIR/books_$TIMESTAMP.db"
```

### Sample Verification Commands

```bash
# 1. Build and start application
./mvnw clean package && docker compose up -d

# 2. Create a book via API
curl -X POST http://localhost:9000/books \
  -H "Content-Type: application/json" \
  -d '{
    "isbn": "978-0134685991",
    "title": "Effective Java",
    "author": "Joshua Bloch",
    "published": "2018-01-06",
    "pages": 416,
    "description": "Best practices for Java programming",
    "website": "https://www.oreilly.com/library/view/effective-java/9780134686097/"
  }'

# 3. Restart container and verify data persists
docker compose restart
sleep 10
curl http://localhost:9000/books/978-0134685991

# 4. Expected: Book data returned (not 404)

# 5. Reset database to original seed data
docker compose down -v
docker compose up -d
```

---

## Acceptance Criteria

- [ ] **All 15+ existing tests pass** without modification (controller, service, repository layers)
- [ ] **Search functionality preserved**: `/books/search?description=java` returns case-insensitive matches
- [ ] **Caching behavior unchanged**: `@Cacheable`, `@CachePut`, `@CacheEvict` annotations work identically
- [ ] **Data persists across restarts**: Books created via POST remain after `docker compose restart`
- [ ] **Test coverage maintained**: JaCoCo reports show 100% coverage for `BooksController` and `BooksService`
- [ ] **Docker health checks pass**: Actuator endpoint `/actuator/health` returns UP status
- [ ] **OpenAPI documentation functional**: Swagger UI at `http://localhost:9000/swagger/index.html` displays all endpoints
- [ ] **No read performance degradation**: GET operations complete within similar response times (±10% tolerance)
- [ ] **Database file created**: `/storage/books-sqlite3.db` exists in Docker volume after first run
- [ ] **Seed data initialization works**: Pre-seeded database is copied on first container run
- [ ] **CI/CD pipeline passes**: GitHub Actions workflow completes successfully (Maven verify, tests, coverage reports)
- [ ] **Backward compatibility considered**: Document any breaking changes or migration steps in `CHANGELOG.md`

---

### 1. SQLite Concurrent Write Limitations
- **Issue**: SQLite uses a single-writer lock, which can cause `SQLITE_BUSY` errors under high concurrent write load
- **Mitigation**: 
  - Acceptable for this demo/POC project (low traffic)
  - Configure `busy_timeout` via connection string: `jdbc:sqlite:/storage/books-sqlite3.db?busy_timeout=5000`
  - Document limitation in README for users considering production use

### 2. Docker Container File Permissions
- **Issue**: SQLite database file must be writable by the `spring` user (non-root)
- **Solution**: 
  - Ensure `/storage` directory ownership: `chown -R spring:spring /storage` in Dockerfile
  - Use Docker volume (not bind mount) to avoid host permission conflicts

### 3. Database File Backup Strategy
- **Recommendation**:
  - Use `docker cp` to export database file from volume
  - Schedule backups if deployed to production (e.g., daily cron job)
  - Consider SQLite's `.backup` command for online backups
  - Document in README: "To backup: `docker cp $(docker compose ps -q api):/storage/books-sqlite3.db ./backup.db`"

### 4. Schema Migration for Existing Data
- **Current**: No existing persistent data (H2 is in-memory)
- **Future**: If migrating from actual H2 data, export to SQL and import to SQLite
- **Hibernate DDL**: `spring.jpa.hibernate.ddl-auto=update` handles schema creation automatically

### 5. Testing Strategy
- **Unit/Integration Tests**: Continue using H2 for fast test execution (profile-based configuration)
- **Manual Testing**: Use SQLite in Docker for local development persistence
- **CI/CD**: Tests run with H2 (faster), Docker image uses SQLite (realistic)

### 6. Database Reset
- **To reset database to seed data**: Run `docker compose down -v` to remove the volume, then `docker compose up -d`
- **The entrypoint script** will detect the missing database file and copy the seed from the `hold/` directory

---

## Rollback Plan

If migration encounters critical issues:

1. **Revert dependency changes** in `pom.xml` (restore H2, remove SQLite)
2. **Restore original `application.properties`** configuration
3. **Re-add `@Lob` annotation** to `Book.description` field
4. **Restore CAST operation** in `BooksRepository` JPQL query
5. **Remove volume configuration** from `Dockerfile` and `compose.yaml`
6. **Remove `storage/` directory** and restore original entrypoint script
7. **Rebuild**: `./mvnw clean package && docker compose up --build`

**Rollback Trigger Conditions:**
- More than 20% test failures
- Performance degradation exceeding 50% on read operations
- Critical bugs discovered in production-like testing
- Community dialect incompatibility issues

---

## Resources

- 🔗 [In-Memory Databases in Java](https://www.baeldung.com/java-in-memory-databases)
- 🔗 [Spring Boot with SQLite](https://www.baeldung.com/spring-boot-sqlite)
- 🔗 [Xerial SQLite JDBC Driver](https://github.com/xerial/sqlite-jdbc)
- 🔗 [Hibernate Community Dialects](https://docs.jboss.org/hibernate/orm/6.2/userguide/html_single/Hibernate_User_Guide.html#database-dialect)
- 🔗 [SQLite Documentation](https://www.sqlite.org/docs.html)
- 🔗 [Docker Volumes](https://docs.docker.com/storage/volumes/)
- 🔗 [Reference Implementation: ts-node-samples-express-restful](https://github.com/nanotaboada/ts-node-samples-express-restful) - TypeScript project using the same pre-seeded SQLite pattern
